name: nullptr

services:
  server:
    image: ghcr.io/fachinformatiker-community/nullptr
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:./dev.db"

      # The Discord bot token and the owner IDs for managing the bot
      DISCORD_BOT_TOKEN:
      DISCORD_OWNER_IDS:

      # Telegram bot token
      TELEGRAM_BOT_TOKEN:

      # MEGA configuration
      MEGA_EMAIL:
      MEGA_PASSWORD:
      MEGA_FOLDER: