name: nullptr

services:
  server:
    image: ghcr.io/fachinformatiker-community/nullptr
    environment:
      # The Discord bot token and the owner IDs for managing the bot
      DISCORD_BOT_TOKEN:
      DISCORD_OWNER_IDS:

      # Telegram bot token (you can use the discord and/or telegram bot by setting the bot token variables)
      TELEGRAM_BOT_TOKEN:

      # MEGA configuration
      MEGA_EMAIL:
      MEGA_PASSWORD:
      MEGA_FOLDER:

    volumes:
      - ./data:/data